# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  planit:
    image: planit
    build:
      context: .
      dockerfile: Plan-It/Dockerfile
    ports:
      - 5261:5261
